### ISSUE TITLE
Booking Validation Problem: What happened when there are multiple solution?

### ISSUE THREAD

**Issue by vinis** [itatsmove/smovechallenge#1]
Do i need to return them all?

**Comment by JamesWooldridge** [comment]
You only need to return one sequence - the one with the best score (i.e. least relocations) that you can find. If you find multiple sequences with the same score, you can return any one of them, it does not matter which.

**Comment by vinis** [comment]
After trying it out, turns out i severely underestimated the problem. This is essentially a topological sorting for directed graph with minimum number of violation, isn't it?

**Comment by JamesWooldridge** [comment]
Topological sort requires the graph to be acyclic, so assuming you can model the input as a DAG, then yes, this approach sounds feasible.

**Comment by vinis** [comment]
Thanks for the reply.

Initially i thought it's just a simple permutation problem due to the keyword specified in description. But since i can't think of a way to avoid brute forcing all permutations, i changed my thinking to graph based. I am now quite confident the better approach is to model the data to graph -> solve the feedback arc set -> topological sort the residue DAG. Just not so sure how to incorporate minimum relocation into the topological sort yet.

This specific problem is uncharted territory for me. Never dealt with any graph problem before. I gotta do some reading/research, pretty sure the community had come up with an efficient algorithm for this problem.

**Comment by JamesWooldridge** [comment]
It’s good that you’re considering performance; this is the kind of thinking that we’re looking for in solving the problem. That said, bear in mind that this is a difficult problem to find an optimal solution for, and we certainly don’t expect a perfect (or overly complicated) algorithm. Something that shows your understanding of the problem, your ability to write elegant and readable code, and your ability to go beyond a basic brute force solution is what we’re after.

Also note that if this particular challenge isn’t best suited to your skill set, you can always try one of the other 3.
